# users password Aa123456
users:
  - username: solar 
    password: $6$6BJHROjeWqufSAYK$50Cq4b5DA46Q/1zfasKKEXvlQTJWc6rLuBNp1w/W3Ue8f7.9nC.8Eu3G9eTWzzUJcNG1aDuazvPJKV0wLPQu.. 
    update_password: always 
    comment: Create user solar 
    shell: /bin/bash
    ssh_key: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQh4Bd/QNWQVylTcDW3rFhVnwzFCuQdrEbRvcOJX9cqRo/48e7GSgnTIs9Dg70NwGp3GqUt1znXz6Rb5ryIHl4C3eqZPwZm5yqPckCEjwj2bQVLgBzrvggJQXiD8vZlOf4rRFnMJYckYZ6in1Rh6Nd5DyZp593RZK2XQyVE05oXGZpRGEUIxsQN/tFXas6vVlMz6XbQgVH/bAXiPMSeTm+OUdMxHiH+uSKWH/JNJN1bbvbHskiIJVOpx6/SoOIUP1717RwpjauElS4zFiSeGKL11Ri7ioM3ow61ZWvXRkerlOn+2Q6MtgqBwQRw4CpH0oq8S8OhzYdpfkekLxJVeJn johnwick@chenjinhaode-MacBook-Pro.local
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtgtkHtkzA0Z+SNRAqQ0lqJNdbcXr5tGJ+h3vWqykz0XokxUxaNt/2SGbF7zme179tErzHFpK1U6mCqqu5eRINVaxe5D17X+Y6Z3RpuEuE6vBbCaqIO4iLNy0lynUZ1T8GRVWLtaJVZz0xF9YYANA5QObpe/Pg38yitpQjFmiBvQyIW5jhNC/qJYWfsKzpLghMVthrCSpc9DwD5AbdcAotQzfGjpOoNNxhXFcFsiLZT5MAqf7NJ0vsSBoVafzdx0zLfjxEWqhtlgvyRoQ2Kq0RdfVyT51UUYMiNCGwjUd+J3rW3uVF6tei17iWGA5EZIaV95AAwe83bVZEPw8LJhHpycbaRtfPUTmclZ+r+SKQ1UfJLEX9ZQwfy/VnhjD5mVlSIUcvIkt5tHiCL3i8hkMtJL/HkYw2j8z7vfejizw5eQrgjPQKcaqt3bK5DQxRaW3NTHr3j47DMg/wD2vOjyMJPw5Yz4JaoxVCgbdpicsYRNzBGsFMW9yxCvVjXUxIGuc= frankie.tseng@solartninc.com
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7AAMP/s3v9XM8S/LW4WzCh2vDIhqncZ5UEdWD/Q/xwYBZ+Mz//JvuAjPfusdLWS2pvu0enxAOSMVgEhUvuC3YzCkcXE4E3aw+dwlokNefSl7RteGukdrNBMjFylsx/IymKaLwZZ8Sag94v0GZBKpyo+CTHBv5WebEmQRItx1dhShCVvxg9hYd9DcpogoXGNFUcziBq2RQy9nNgvBqwmaXP2Lu90JjIXgNSa6iXHH+SyNpVwRFcg/cDzyFD/zCCCumerxNU3yxAADUmKeMrUH7yXlawly5ci0yDCj2mtYx7Apom72Ynb+KKnO+fopxlFztUeb2ijJ024sc9tRJgMJD kyle.tong0609@gmail.com
    exclusive_ssh_key: yes 
    user_state: present
    use_sudo: yes 
    use_sudo_nopass: no
    user_state: present
    servers:
        - solar_* 
# https://github.com/ryandaniels/ansible-role-create-users
# docker

docker_users: solar 

# https://github.com/geerlingguy/ansible-role-docker
# CentOS 

centos_base_enable_epel: true
centos_base_basic_packages: true
centos_base_secure_sshd: true
centos_base_basic_vim_tweaks: true
centos_base_htop_configuration: true
centos_base_fail2ban_configuration: true
centos_base_selinux_packages: true
centos_base_firewalld_services: ['http', 'https']
centos_base_vim_users: ['root','solar']

# https://github.com/bngsudheer/ansible-role-centos_base
oh_my_zsh_theme: cloud 
oh_my_zsh_plugins:
    - git
#https://github.com/gantsign/ansible-role-oh-my-zsh
