- hosts: solar_*
  gather_facts: true
  become: yes
  vars_files:
    - "vars/solar_base.yml"
  roles:
    - users
    - timezone
    - centos 
    - docker-centos
    - role: oh-my-zsh-centos
      users:
        - username: solar 
